---
dependency:
  name: galaxy
driver:
  name: docker

# lint: |
#   set -e
#   yamllint .
#   ansible-lint
#   flake8

platforms:
  - name: instance-${TOX_ENVNAME}
    image: ${MOLECULE_DISTRO:-'centos:7'}
    command: ${MOLECULE_DOCKER_COMMAND:-'/sbin/init'}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    # registry:
    #   url: registry.example.com
    #   credentials:
    #     username: $USERNAME
    #     passsword: $PASSWORD
    #     email: user@example.com
    # env:
    #   FOO: bar

provisioner:
  name: ansible
  log: true
verifier:
  name: testinfra
